
version: '3.8'
services:
  postgres:
    image: postgres
    container_name: phonebook_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: PhoneBookDb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: phonebook_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
